### ISSUE TITLE
Issue with multiple hour classes that are split data not story

### ISSUE THREAD

**Issue by rileyvh6** [qiaoli116/auto-attendance#3]
Hi Qiao
Great extension, I thought I would let you know I found an instance were your extension isn't working correctly. Classes with multiple hour values that are split on a single day don't appear to store information correctly.

![attendance](https://user-images.githubusercontent.com/31227705/64226070-416c5580-cf21-11e9-8d60-5bc00b654143.PNG)

Small problem, if there's a fix great, if not I can keep using the plugin I have been using "Form save and Restore", which works in this case.

**Comment by qiaoli116** [comment]
Hi, Riley (?), please check out commit [cfe6626 ](https://github.com/qiaoli116/auto-attendance/commit/cfe66267bb0ff6ade24a8da02bdbfc3446973578) for the update. In this update, Student id, CRN date and start time are all used to identify a row. This solution solved the issue. Please test the solution and let me know if it works.
